'use client';

import { useState } from 'react';
import { TermsLayout } from './TermsStyle';
import { LuScale, LuArrowLeft } from 'react-icons/lu';

export const TermsOfService = () => {
	const currentYear = new Date().getFullYear();
	const [mobileView, setMobileView] = useState<'sidebar' | 'content'>(
		'sidebar',
	);

	const termsSections = [
		{
			id: '1-acceptance',
			title: '1. Acceptance of Terms',
			content:
				'By accessing or utilizing the engineering, alternative power installations, or ICT network architectures provided by FENERJ Engineering Services Ltd ("Company", "We", "Us"), you explicitly agree to be bound by these legal Terms of Service. If you do not agree with any structural provision contained herein, you must immediately halt all platform interactions and service usage.',
		},
		{
			id: '2-scope',
			title: '2. Scope of Services',
			content:
				'FENERJ provides technical infrastructure management, VSAT configuration setup arrays, specialized electronic document management systems (EDMS), and hybrid solar power procurement layouts. All formal projects are governed additionally by custom executed Service Level Agreements (SLAs) which take structural precedence over these generalized terms.',
		},
		{
			id: '3-intellectual',
			title: '3. Intellectual Property Rights',
			content:
				'Unless stated explicitly in a separate vendor contract, all structural engineering blueprints, system design logic, custom software algorithms, and visual UI layouts generated by FENERJ personnel remain the exclusive intellectual property of FENERJ Engineering Services Ltd.',
		},
		{
			id: '4-liabilities',
			title: '4. Limitation of Liability',
			content:
				'In no event shall FENERJ or its certified technical engineering leads be liable for any indirect, circumstantial, punitive, or consequential operational data losses arising from network latency updates, custom firewall tests, or equipment downtime events outside our immediate control paths.',
		},
		{
			id: '5-governing',
			title: '5. Governing Law',
			content:
				'These platform terms and technical service agreements are construed, validated, and strictly executed under the structural federal frameworks and judicial arbitration laws of the Federal Republic of Nigeria, with primary legal jurisdiction held in Abuja.',
		},
	];

	const handleMobileNav = (sectionId: string) => {
		setMobileView('content');
		setTimeout(() => {
			const target = document.getElementById(sectionId);
			if (target) {
				target.scrollIntoView({ behavior: 'smooth', block: 'start' });
			}
		}, 100);
	};

	return (
		<TermsLayout $viewState={mobileView}>
			<div className="terms-container">
				<div className="mobile-header-toggle">
					{mobileView === 'content' ? (
						<button
							className="toggle-btn"
							onClick={() => setMobileView('sidebar')}
						>
							<LuArrowLeft /> Back to Table of Contents
						</button>
					) : (
						<div className="mobile-title-banner">
							<LuScale /> FENERJ Legal Overview
						</div>
					)}
				</div>

				<div className="split-grid-wrapper">
					<aside className="toc-sidebar">
						<div className="sidebar-sticky-node">
							<div className="sidebar-brand-title">
								<LuScale className="scale-icon" />
								<h3>Legal Terms</h3>
							</div>
							<p className="last-updated">Last updated: June 2026</p>

							<nav className="toc-navigation-links">
								{termsSections.map((sec) => (
									<button
										key={sec.id}
										className="toc-anchor-link"
										onClick={() => handleMobileNav(sec.id)}
									>
										{sec.title}
									</button>
								))}
							</nav>
						</div>
					</aside>

					<main className="legal-content-pane">
						<header className="content-intro">
							<h1>Terms of Service</h1>
							<p>
								Please review these legal parameters detailing your operational
								rights and structural compliance limits under FENERJ
								infrastructures.
							</p>
						</header>

						<div className="document-body">
							{termsSections.map((sec) => (
								<section
									id={sec.id}
									key={sec.id}
									className="document-node-section"
								>
									<h2>{sec.title}</h2>
									<p>{sec.content}</p>
								</section>
							))}
						</div>

						<footer className="document-closure-notice">
							<p>
								&copy; {currentYear} FENERJ Engineering Services Ltd. Plot 142,
								Ademola Adetokunbo Crescent, Wuse II, Abuja.
							</p>
						</footer>
					</main>
				</div>
			</div>
		</TermsLayout>
	);
};
